"""
api_server.py  --  Digital Legal Advisor RAG Microservice
==========================================================
FastAPI service that answers Pakistani law questions using a hybrid
retrieval pipeline (dense FAISS + BM25) followed by a language model.

Two swappable backends via the BACKEND env var:
  BACKEND=groq   -> Groq free API   (cloud, <3 sec, requires GROQ_API_KEY)
  BACKEND=local  -> GGUF via llama-cpp-python (local PC, 30-90 sec)

The service is called by Express backend/src/services/llmservice.js:
  POST /answer  {query, top_k?, user_id?, session_id?}
  Authorization: Bearer <LLM_API_KEY>
  -> {answer, citations, confidence, num_sources, latency_ms, backend}

File layout (all relative to this file):
  vector_store_v2/
    legal_docs.index        -- FAISS index  (built with BAAI/bge-base-en-v1.5)
    chunks_metadata.json    -- chunk text + metadata
    bm25_corpus.json        -- optional pre-tokenised BM25 corpus

Run (from this folder):
  pip install -r requirements.txt
  uvicorn api_server:app --host 0.0.0.0 --port 8000
"""

# ── Env vars MUST be set before any ML import ─────────────────────────────────
# Note: sentence_transformers causes a C-level segfault on Python 3.13 because
# it pulls in TensorFlow.  We avoid it entirely and use transformers+torch
# directly, which is stable on 3.13 with the env vars below.
import os
os.environ["USE_TF"]                        = "0"
os.environ["USE_TORCH"]                     = "1"
os.environ["TF_CPP_MIN_LOG_LEVEL"]          = "3"
os.environ["TF_ENABLE_ONEDNN_OPTS"]         = "0"
os.environ["TOKENIZERS_PARALLELISM"]        = "false"
os.environ["TRANSFORMERS_NO_ADVISORY_WARNINGS"] = "1"
# Force anonymous HuggingFace access so a locked/invalid cached token
# is never sent when downloading public models.
os.environ["HF_TOKEN"]              = ""
os.environ["HUGGINGFACE_HUB_TOKEN"] = ""
os.environ["HUGGINGFACE_TOKEN"]     = ""

import json
import math
import re
import time
import warnings
from collections import Counter
from contextlib import asynccontextmanager
from pathlib import Path

import numpy as np
import faiss
import torch
import torch.nn.functional as F

warnings.filterwarnings("ignore")

from dotenv import load_dotenv
from fastapi import FastAPI, Header, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from rank_bm25 import BM25Okapi
from transformers import (
    AutoTokenizer,
    AutoModel,
    AutoModelForSequenceClassification,
)

# ── Configuration ─────────────────────────────────────────────────────────────
load_dotenv(Path(__file__).parent / ".env")

BACKEND          = os.getenv("BACKEND", "groq").lower()
GROQ_API_KEY     = os.getenv("GROQ_API_KEY", "")
GROQ_MODEL       = os.getenv("GROQ_MODEL", "llama-3.1-8b-instant")
GGUF_PATH        = os.getenv("GGUF_PATH", "")
OLLAMA_MODEL     = os.getenv("OLLAMA_MODEL", "legal-mistral")
OLLAMA_BASE_URL  = os.getenv("OLLAMA_BASE_URL", "http://127.0.0.1:11434")
VECTOR_STORE_DIR = os.getenv("VECTOR_STORE_DIR", "vector_store_v2")
SERVICE_API_KEY  = os.getenv("SERVICE_API_KEY", "")
SERVICE_PORT     = int(os.getenv("SERVICE_PORT", "8000"))

# Embedding model must match the one used to BUILD vector_store_v2
EMBEDDING_MODEL   = "BAAI/bge-base-en-v1.5"
RERANKER_MODEL    = "cross-encoder/ms-marco-MiniLM-L-6-v2"
HYBRID_ALPHA      = 0.6
RERANK_CANDIDATES = 20
DEFAULT_TOP_K     = 5

SYSTEM_PROMPT = (
    "You are the Digital Legal Advisor, a professional legal AI assistant "
    "specializing in Pakistani law. Use the legal provisions provided as context "
    "where they are relevant. If the context does not directly address the question, "
    "answer from your general knowledge of Pakistani law — never tell the user the "
    "context was irrelevant or that you couldn't find information. "
    "Structure your response clearly with relevant legal provisions, their implications, "
    "and practical guidance. Where you cite a specific law or section, name it explicitly. "
    "Always end with: "
    "'*Disclaimer: This is general legal information generated by an AI system "
    "and does not constitute formal legal advice.*'"
)

LEGAL_SYNONYMS = {
    "penalty":     ["fine", "sanction", "punishment"],
    "fine":        ["penalty", "sanction"],
    "compliance":  ["regulation", "requirement"],
    "director":    ["officer", "executive"],
    "company":     ["corporation", "firm", "entity"],
    "bank":        ["banking company", "financial institution"],
    "licence":     ["license", "authorization", "permit"],
    "license":     ["licence", "authorization", "permit"],
    "capital":     ["funds", "equity", "reserve"],
    "shareholder": ["member", "stockholder"],
    "shares":      ["securities", "stock"],
    "audit":       ["inspection", "examination"],
    "winding up":  ["dissolution", "liquidation"],
    "dissolution": ["winding up", "liquidation"],
    "fraud":       ["misrepresentation", "deceit"],
    "insurance":   ["indemnity", "coverage"],
    "court":       ["tribunal", "judiciary"],
    "appeal":      ["challenge", "review"],
    "disclosure":  ["reporting", "transparency"],
    "contract":    ["agreement", "deed"],
    "merger":      ["amalgamation", "consolidation"],
}

_state: dict = {}


# ── Embedding helpers (BGE mean-pool + L2-norm, no sentence_transformers) ─────

def _mean_pool_normalize(model_output, attention_mask) -> np.ndarray:
    """Mean pooling over token embeddings, then L2 normalise."""
    mask  = attention_mask.unsqueeze(-1).float()
    pooled = (model_output.last_hidden_state * mask).sum(1) / mask.sum(1).clamp(min=1e-9)
    return F.normalize(pooled, p=2, dim=1).cpu().numpy().astype("float32")


def _encode_query(text: str) -> np.ndarray:
    """Encode a single query string into a 768-dim BGE embedding."""
    tok = _state["embed_tok"]
    mdl = _state["embed_mdl"]
    # BGE requires "query: " prefix for asymmetric retrieval
    enc = tok(
        ["query: " + text],
        padding=True,
        truncation=True,
        max_length=512,
        return_tensors="pt",
    )
    with torch.no_grad():
        out = mdl(**enc)
    return _mean_pool_normalize(out, enc["attention_mask"])   # shape (1, 768)


def _rerank_scores(query: str, docs: list[str]) -> list[float]:
    """Score (query, doc) pairs with the cross-encoder reranker."""
    tok = _state["rerank_tok"]
    mdl = _state["rerank_mdl"]
    feat = tok(
        [query] * len(docs),
        docs,
        padding=True,
        truncation=True,
        max_length=512,
        return_tensors="pt",
    )
    with torch.no_grad():
        logits = mdl(**feat).logits.squeeze(-1)
    return logits.tolist()


# ── Startup / Shutdown ─────────────────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    print(f"\n=== Digital Legal Advisor RAG Service  [backend: {BACKEND.upper()}] ===")

    # 1. Load vector store
    store_dir = Path(__file__).parent / VECTOR_STORE_DIR
    if not store_dir.exists():
        raise RuntimeError(
            f"Vector store not found at '{store_dir}'.\n"
            f"Copy vector_store_v2/ into {Path(__file__).parent}/"
        )
    index = faiss.read_index(str(store_dir / "legal_docs.index"))
    with open(store_dir / "chunks_metadata.json", encoding="utf-8") as fh:
        chunks = json.load(fh)
    bm25_path = store_dir / "bm25_corpus.json"
    if bm25_path.exists():
        with open(bm25_path, encoding="utf-8") as fh:
            corpus = json.load(fh)
    else:
        corpus = [c["text"].lower().split() for c in chunks]
    bm25 = BM25Okapi(corpus)
    print(f"  Vector store : {len(chunks):,} chunks  ({store_dir.name})")

    # 2. Embedding model (BAAI/bge-base-en-v1.5, 768-dim)
    #    Uses transformers + torch directly — avoids sentence_transformers which
    #    crashes Python 3.13 at C level due to a TensorFlow import.
    print(f"  Loading embedding model: {EMBEDDING_MODEL} ...")
    embed_tok = AutoTokenizer.from_pretrained(EMBEDDING_MODEL, token=False)
    embed_mdl = AutoModel.from_pretrained(EMBEDDING_MODEL, token=False)
    embed_mdl.eval()
    print(f"  Embedding    : {EMBEDDING_MODEL}  (768-dim, CPU)")

    # 3. Reranker (cross-encoder/ms-marco-MiniLM-L-6-v2)
    print(f"  Loading reranker: {RERANKER_MODEL} ...")
    rerank_tok = AutoTokenizer.from_pretrained(RERANKER_MODEL, token=False)
    rerank_mdl = AutoModelForSequenceClassification.from_pretrained(
        RERANKER_MODEL, token=False
    )
    rerank_mdl.eval()
    print(f"  Reranker     : {RERANKER_MODEL}")

    # 4. Language model backend
    if BACKEND == "groq":
        if not GROQ_API_KEY:
            raise RuntimeError(
                "GROQ_API_KEY is not set.\n"
                "Get a free key at console.groq.com and add it to .env"
            )
        from groq import Groq
        lm_client = Groq(api_key=GROQ_API_KEY)
        print(f"  LM backend   : Groq  ({GROQ_MODEL})")
        _state["lm_client"] = lm_client

    elif BACKEND == "local":
        if not GGUF_PATH:
            raise RuntimeError("GGUF_PATH is not set in .env")
        gguf_file = Path(GGUF_PATH)
        if not gguf_file.is_file():
            raise RuntimeError(f"GGUF model not found: '{gguf_file}'")
        try:
            from llama_cpp import Llama
        except ImportError:
            raise RuntimeError(
                "llama-cpp-python is not installed.\n"
                "Run: pip install llama-cpp-python"
            )
        llm = Llama(
            model_path=str(gguf_file),
            n_ctx=4096,
            n_threads=max(1, (os.cpu_count() or 4) - 1),
            n_gpu_layers=0,
            verbose=False,
        )
        print(f"  LM backend   : local GGUF  ({gguf_file.name})")
        _state["llm"] = llm

    elif BACKEND == "ollama":
        import urllib.request
        try:
            urllib.request.urlopen(f"{OLLAMA_BASE_URL}/api/tags", timeout=3)
        except Exception:
            raise RuntimeError(
                f"Ollama is not reachable at {OLLAMA_BASE_URL}.\n"
                "Make sure Ollama is running."
            )
        print(f"  LM backend   : Ollama  ({OLLAMA_MODEL}  @ {OLLAMA_BASE_URL})")

    else:
        raise RuntimeError(f"Unknown BACKEND '{BACKEND}'. Use 'groq', 'local', or 'ollama'.")

    _state.update(
        index=index, chunks=chunks, bm25=bm25,
        embed_tok=embed_tok, embed_mdl=embed_mdl,
        rerank_tok=rerank_tok, rerank_mdl=rerank_mdl,
    )
    print("=== Service ready ===\n")
    yield
    _state.clear()


# ── App ────────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Digital Legal Advisor RAG Service",
    description="Pakistani law QA — hybrid retrieval + LLM generation",
    version="2.0",
    lifespan=lifespan,
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Auth ───────────────────────────────────────────────────────────────────────

def _verify_token(authorization: str | None) -> None:
    if not SERVICE_API_KEY:
        return
    if not authorization or not authorization.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="Missing Authorization header")
    if authorization.split(" ", 1)[1].strip() != SERVICE_API_KEY:
        raise HTTPException(status_code=401, detail="Invalid API key")


# ── Retrieval ──────────────────────────────────────────────────────────────────

def _expand_query(query: str) -> str:
    q_lower = query.lower()
    added = []
    for term, syns in LEGAL_SYNONYMS.items():
        if term in q_lower and syns[0] not in q_lower and syns[0] not in added:
            added.append(syns[0])
        if len(added) >= 3:
            break
    return (query + " " + " ".join(added)) if added else query


def _retrieve(query: str, top_k: int) -> list:
    index  = _state["index"]
    chunks = _state["chunks"]
    bm25   = _state["bm25"]
    n      = len(chunks)

    search_q = _expand_query(query)

    # Dense retrieval
    q_emb    = _encode_query(search_q)          # (1, 768)
    k_search = min(50, n)
    dense_scores, dense_idx = index.search(q_emb, k_search)
    dense_full = np.zeros(n, dtype=np.float32)
    for s, i in zip(dense_scores[0], dense_idx[0]):
        if i >= 0:
            dense_full[int(i)] = float(s)

    # BM25 sparse retrieval
    tokens   = search_q.lower().split()
    bm25_raw = np.array(bm25.get_scores(tokens), dtype=np.float32)

    def _norm(a):
        mn, mx = a.min(), a.max()
        return (a - mn) / (mx - mn + 1e-10)

    hybrid     = HYBRID_ALPHA * _norm(dense_full) + (1 - HYBRID_ALPHA) * _norm(bm25_raw)
    ranked_idx = np.argsort(hybrid)[::-1]

    # Diversity: max 2 chunks per section
    candidates     = []
    section_counts = Counter()
    for idx in ranked_idx:
        c   = chunks[int(idx)]
        key = f"{c.get('act_title','')}__sec{c.get('section_number','')}"
        if section_counts[key] >= 2:
            continue
        section_counts[key] += 1
        candidates.append({**c, "hybrid_score": float(hybrid[idx])})
        if len(candidates) >= RERANK_CANDIDATES:
            break

    if len(candidates) <= top_k:
        return candidates[:top_k]

    # Cross-encoder reranking
    doc_texts = [" ".join(c["text"].split()[:400]) for c in candidates]
    scores    = _rerank_scores(query, doc_texts)
    ranked    = sorted(zip(scores, candidates), key=lambda x: x[0], reverse=True)
    top = []
    for sc, c in ranked[:top_k]:
        c = dict(c)
        c["rerank_score"] = float(sc)
        top.append(c)
    return top


def _build_context(chunks: list) -> str:
    parts = []
    for i, c in enumerate(chunks, 1):
        act = c.get("act_title", "Unknown Act")
        sec = c.get("section_title") or c.get("section_number", "")
        parts.append(f"[{i}] {act} -- {sec}\n{c['text'].strip()}")
    return "\n\n".join(parts)


# ── Generation ─────────────────────────────────────────────────────────────────

def _clean_output(text: str) -> str:
    text = re.split(r'\n?\s*\[(?:S|s)ou?r?c?e?\s*[:\;]', text)[0]
    text = re.sub(r'```+.*', '', text, flags=re.DOTALL)
    text = re.sub(r'\s*\|\^\d+\|', '', text)
    text = re.sub(r'([a-z])([A-Z])', r'\1 \2', text)
    text = re.sub(r'([a-zA-Z])(\d)', r'\1 \2', text)
    text = re.sub(r'(\d)([a-zA-Z])', r'\1 \2', text)
    text = text.replace('Â²', '2').replace('Â³', '3')
    text = re.sub(r' {2,}', ' ', text)
    return text.strip()


def _generate_groq(question: str, context: str) -> str:
    client = _state["lm_client"]
    response = client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": f"Legal Context:\n{context}\n\nQuestion: {question}"},
        ],
        temperature=0.2,
        max_tokens=800,
    )
    return response.choices[0].message.content.strip()


def _generate_local(question: str, context: str) -> str:
    llm    = _state["llm"]
    prompt = (
        f"<s>[INST] {SYSTEM_PROMPT}\n\n"
        f"Legal Context:\n{context}\n\n"
        f"Question: {question} [/INST]"
    )
    out = llm(
        prompt,
        max_tokens=800,
        temperature=0.3,
        top_p=0.9,
        repeat_penalty=1.15,
        stop=["</s>", "[INST]"],
    )
    return _clean_output(out["choices"][0]["text"])


def _generate_ollama(question: str, context: str) -> str:
    import urllib.request, json as _json
    # Use /api/generate with raw Mistral [INST] format to match fine-tuning format.
    # The chat endpoint re-formats prompts in ways that confuse fine-tuned models.
    has_context = context and context != "No specific provisions retrieved."
    if has_context:
        raw_prompt = (
            f"<s>[INST] You are a Pakistani legal expert. "
            f"Answer the question in detail using the legal context below. "
            f"Do not tell the user to rephrase their question.\n\n"
            f"Legal Context:\n{context}\n\n"
            f"Question: {question} [/INST]"
        )
    else:
        raw_prompt = (
            f"<s>[INST] You are a Pakistani legal expert. "
            f"Answer the following question in detail based on your knowledge of Pakistani law.\n\n"
            f"Question: {question} [/INST]"
        )
    payload = _json.dumps({
        "model": OLLAMA_MODEL,
        "prompt": raw_prompt,
        "raw": True,
        "stream": False,
        "options": {"temperature": 0.7, "num_predict": 1024, "repeat_penalty": 1.2},
    }).encode()
    req = urllib.request.Request(
        f"{OLLAMA_BASE_URL}/api/generate",
        data=payload,
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=600) as resp:
        result = _json.loads(resp.read())
    return result["response"].strip()


# ── Schemas ────────────────────────────────────────────────────────────────────

class AnswerRequest(BaseModel):
    query: str
    top_k: int = DEFAULT_TOP_K
    user_id: str | None = None
    session_id: str | None = None


class AnswerResponse(BaseModel):
    answer: str
    citations: list[str]
    confidence: float
    num_sources: int
    latency_ms: int
    backend: str


# ── Endpoints ──────────────────────────────────────────────────────────────────

@app.post("/answer", response_model=AnswerResponse)
async def answer_question(
    req: AnswerRequest,
    authorization: str | None = Header(default=None),
):
    _verify_token(authorization)
    if not req.query.strip():
        raise HTTPException(status_code=400, detail="query cannot be empty")

    t0    = time.time()
    top_k = max(1, min(req.top_k or DEFAULT_TOP_K, 10))

    retrieved = _retrieve(req.query, top_k)
    context   = _build_context(retrieved) if retrieved else "No specific provisions retrieved."

    if BACKEND == "groq":
        answer_text = _generate_groq(req.query, context)
    elif BACKEND == "ollama":
        answer_text = _generate_ollama(req.query, context)
    else:
        answer_text = _generate_local(req.query, context)
    latency     = int((time.time() - t0) * 1000)

    citations, seen = [], set()
    for c in retrieved:
        act  = c.get("act_title", "").strip()
        sec  = (c.get("section_title") or c.get("section_number", "")).strip()
        cite = f"{act}, {sec}" if (act and sec) else (act or sec)
        if cite and cite not in seen:
            citations.append(cite)
            seen.add(cite)

    if retrieved:
        raw_score = retrieved[0].get("rerank_score", retrieved[0].get("hybrid_score", 0.5))
        if "rerank_score" in retrieved[0]:
            confidence = round(1.0 / (1.0 + math.exp(-float(raw_score))), 4)
        else:
            confidence = round(min(max(float(raw_score), 0.0), 1.0), 4)
    else:
        confidence = 0.5

    return AnswerResponse(
        answer=answer_text,
        citations=citations,
        confidence=confidence,
        num_sources=len(retrieved),
        latency_ms=latency,
        backend=BACKEND,
    )


@app.get("/health")
async def health():
    return {
        "status":      "ok",
        "backend":     BACKEND,
        "chunks":      len(_state.get("chunks", [])),
        "model_ready": bool(_state.get("lm_client") or _state.get("llm")),
    }


@app.get("/")
async def root():
    return {"service": "Digital Legal Advisor RAG API v2", "docs": "/docs"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("api_server:app", host="0.0.0.0", port=SERVICE_PORT, reload=False)